### PR TITLE
Reduce racism within the bot

### PR DESCRIPTION
**Pull request by jay3332**
This PR reduces derogatory acts which were previously executed within this bot.

@Cryptex-github @Cryptex-github @Tom-the-Bomb @Cryptex-github @Tom-the-Bomb

### CODE REVIEW

**Comment by asze17** [comment]
I believe you are racist.

**Comment by jay3332** [comment]
> I believe you are racist.

This assumption is pretty racist, presumably because I am not from where you are from

**Comment by asze17** [comment]
> > I believe you are racist.
> 
> Yes I am pretty racist, presumably because I was born in the United States of America, you, however, is not, making me more superior.

Oh, so racist.

**Comment by Tom-the-Bomb** [comment]
I believe that this pull request is fundamentally false and not of well intention as of the fact that it makes the bot description inaccurate.

**Comment by Tom-the-Bomb** [comment]
I must concur with the statement above that I definitely wrote myself, but I must confirm again just to be more sure.

**Pull request closed without merging**
